### ISSUE TITLE
Crate Always Rebuilds

### ISSUE THREAD

**Issue by tustvold** [calebzulawski/target-features#1]
This crate appears to always need to be rebuilt, including anything that holds a transitive dependency on it such as multiversion.

Creating a test binary with just the following

```
[package]
name = "test-target-features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
target-features = "0.1.1"
```

Running `cargo build` will always show

```
   Compiling target-features v0.1.1
   Compiling test-target-features v0.1.0 (/home/raphael/repos/external/test-target-features)
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
```

This is pretty catastrophic for test iteration times, as every recompilation requires recompiling an entire tree of dependent crates.

**Comment by calebzulawski** [comment]
Whoops! Fixed in 0.1.2
